### ISSUE TITLE
Can't install oseti

### ISSUE THREAD

**Issue by tam-nguyenminh** [ikegami-yukino/oseti#7]
Dears,

Thanks for your work on this.
No matter how hard I tried, I still couldn't install oseti in my pip. 
Already install Mecab 
pip install mecab-python3
Already installed the library pip install unidic-lite

And got alert while trying to install oseti. Don't know what's wrong and couldn't find any websites help.

`Collecting oseti
  Using cached oseti-0.4.2-py3-none-any.whl
Collecting bunkai (from oseti)
  Using cached bunkai-1.5.7-py3-none-any.whl (62 kB)
Collecting mecab (from oseti)
  Using cached mecab-0.996.3.tar.gz (62 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\84393\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\84393\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\84393\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\84393\AppData\Local\Temp\pip-build-env-403gl79u\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\84393\AppData\Local\Temp\pip-build-env-403gl79u\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\84393\AppData\Local\Temp\pip-build-env-403gl79u\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\84393\AppData\Local\Temp\pip-build-env-403gl79u\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 35, in <module>
      RuntimeError: Please install MeCab 64-bit binary: https://github.com/ikegami-yukino/mecab/releases
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

Thanks a lot for your help.

**Comment by ikegami-yukino** [comment]
@tam-nguyenminh 
I see.
You should watch out for error messages.
For the present, you can install oseti by uninstalling original MeCab binary (32-bit) and mecab-python3 and then installing [MeCab 64-bit binary for Windows](https://github.com/ikegami-yukino/mecab/releases).

Of course, I will address this issue later.

**Comment by tam-nguyenminh** [comment]
Thanks a lot for your response.
Did what you told. But I got other alerts.
It could be me because I'm newbie to NLP. 
Best

**Comment by ikegami-yukino** [comment]
What version is your Python?
Currently, [mecab](https://pypi.org/project/mecab/) for Python binding is not provided Python 3.11 wheel.
Thus, C++ build tool is required to Compile from source.

**Comment by tam-nguyenminh** [comment]
Aaaah that could be the reason. yes, mine is python 3.11.1 :(
And which version of build tools should be used for compatible with oseti, please? 2019?
Thanks a lot!

**Comment by tam-nguyenminh** [comment]
Hi again,
Maybe you've fixed it or it could be me. Successfully installed now. :)
Thanks a lot.
